"""empty message

Revision ID: 6b10c52d5cc5
Revises: f71cc4107a70
Create Date: 2022-08-22 23:06:56.889643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b10c52d5cc5'
down_revision = 'f71cc4107a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'country', ['country'])
    op.create_unique_constraint(None, 'region', ['region'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'region', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    # ### end Alembic commands ###
