"""empty message

Revision ID: 7ca51a998a77
Revises: af27e834a6e3
Create Date: 2022-08-22 22:55:16.946346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ca51a998a77'
down_revision = 'af27e834a6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('updated', sa.String(length=80), nullable=False))
    op.drop_column('country', 'created_at')
    op.drop_column('country', 'updated_at')
    op.add_column('region', sa.Column('updated', sa.String(length=80), nullable=False))
    op.drop_column('region', 'created_at')
    op.drop_column('region', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('region', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('region', 'updated')
    op.add_column('country', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('country', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('country', 'updated')
    # ### end Alembic commands ###
