"""empty message

Revision ID: af27e834a6e3
Revises: 
Create Date: 2022-08-22 22:36:28.476931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af27e834a6e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('recovered', sa.String(length=200), nullable=False),
    sa.Column('confirmed', sa.String(length=200), nullable=False),
    sa.Column('deaths', sa.String(length=200), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('sq_km_area', sa.Integer(), nullable=False),
    sa.Column('life_expectancy', sa.String(length=80), nullable=False),
    sa.Column('elevation_in_meters', sa.String(length=80), nullable=True),
    sa.Column('continent', sa.String(length=80), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('iso', sa.Integer(), nullable=False),
    sa.Column('capital_city', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.String(length=80), nullable=False),
    sa.Column('long', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.Column('recovered', sa.String(length=200), nullable=False),
    sa.Column('confirmed', sa.String(length=200), nullable=False),
    sa.Column('deaths', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.String(length=80), nullable=False),
    sa.Column('long', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region')
    op.drop_table('country')
    # ### end Alembic commands ###
