"""empty message

Revision ID: f71cc4107a70
Revises: 7ca51a998a77
Create Date: 2022-08-22 23:02:08.644375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71cc4107a70'
down_revision = '7ca51a998a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'country',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('country', 'recovered',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('country', 'confirmed',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('country', 'deaths',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('country', 'population',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('country', 'sq_km_area',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('country', 'life_expectancy',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('country', 'continent',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('country', 'abbreviation',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('country', 'location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('country', 'iso',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('country', 'capital_city',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('country', 'lat',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('country', 'long',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('country', 'updated',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('region', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('region', 'region',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('region', 'recovered',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('region', 'confirmed',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('region', 'deaths',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('region', 'lat',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('region', 'long',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('region', 'updated',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('region', 'updated',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('region', 'long',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('region', 'lat',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('region', 'deaths',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('region', 'confirmed',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('region', 'recovered',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('region', 'region',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('region', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('country', 'updated',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('country', 'long',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('country', 'lat',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('country', 'capital_city',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('country', 'iso',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('country', 'location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('country', 'abbreviation',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('country', 'continent',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('country', 'life_expectancy',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('country', 'sq_km_area',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('country', 'population',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('country', 'deaths',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('country', 'confirmed',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('country', 'recovered',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('country', 'country',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
